# apiVersion: v1
# kind: Service
# metadata:
#   name: server-service
# spec:
#   type: NodePort
#   selector:
#     app: server
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000